version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: espanso-dictionary
    path: ./.vscode/espanso-dictionary.txt
    addWords: true
dictionaries:
  - espanso-dictionary
ignoreWords: []
import: []
