# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: build

  setup:
    status:
      - cargo make --version
      - rust-script --version
    cmds:
      - rustup update
      - cargo install rust-script
      - cargo install cargo-make
    silent: false

  resources:
    deps: [setup]
    cmds:
      - cargo make --profile release -- build-windows-resources

  build:
    deps: [resources]
    cmds:
      - cargo make --profile release -- build-binary 
      - cargo make --profile release -- build-windows-portable
      - cargo make --profile release -- test-binary

  run:
    deps: [setup]
    cmds:
      - cargo make --profile release -- run-binary 

  build-installer:
    deps: [setup]
    cmds:
      - cargo make --profile release -- build-windows-installer 

  build-portable:
    deps: [setup]
    cmds:
      - cargo make --profile release -- build-windows-portable 

  create-bundle:
    deps: [setup]
    cmds:
      - cargo make --profile release -- create-bundle 
