# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: run

  setup:
    status:
      - cargo make --version
      - rust-script --version
    cmds:
      - rustup update
      - cargo install rust-script
      - cargo install cargo-make
    silent: false

  resources:
    deps: [setup]
    sources:
      - ./Cargo.*
      - ./espanso-*/**/*.rs
    generates:
      - ./target/windows/resources/*
    cmds:
      - cargo make --profile release -- build-windows-resources

  build:
    deps: [resources]
    sources:
      - ./Cargo.*
      - ./espanso-*/**/*.rs
    generates:
      - ./target/release/espanso*
    cmds:
      - cargo make --profile release -- build-binary

  release:
    deps: [build]
    cmds:
      - cargo make --profile release -- build-windows-portable

  test:
    deps: [build]
    cmds:
      - cargo make --profile release -- test-binary

  run:
    deps: [build]
    dir: ./target/release
    cmds:
      - ./espanso {{.CLI_ARGS}}

  run-binary:
    deps: [setup]
    cmds:
      - cargo make --profile release -- run-binary

  build-installer:
    deps: [setup]
    cmds:
      - cargo make --profile release -- build-windows-installer

  build-portable:
    deps: [setup]
    cmds:
      - cargo make --profile release -- build-windows-portable

  create-bundle:
    deps: [setup]
    cmds:
      - cargo make --profile release -- create-bundle
